  [build]
  builder = "NIXPACKS"
  nixpacksPlan = { phases = { install = { cmds = ["npm install -g pnpm", "pnpm install"] } } }

  [deploy]
  preDeployCommand = "pnpm exec prisma migrate deploy"
  startCommand = "pnpm run start:prod"