  [build]
  builder = "NIXPACKS"
  nixpacksPlan = { phases = { install = { cmds = ["npm i -g pnpm", "pnpm install --no-frozen-lockfile"] } } }

  [deploy]
  preDeployCommand = "pnpm exec prisma migrate deploy"
  startCommand = "pnpm run start:prod"