  [build]
  builder = "NIXPACKS"
  nixpacksPlan = { phases = { install = { cmds = ["npm i -g pnpm", "pnpm install --no-frozen-lockfile"] } } }

  [deploy]
  startCommand = "node .next/standalone/server.js"